### ISSUE TITLE
Implement a function that draws x number of boxes to visualize a fraction

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/visual-fractions#1]
Per our brainstorming today:

![20170102_144129](https://cloud.githubusercontent.com/assets/1555022/21597919/475157ae-d107-11e6-93e1-1e6f64446a0f.jpg)

![20170102_141555](https://cloud.githubusercontent.com/assets/1555022/21597918/47506b28-d107-11e6-939f-01d1caaa4122.jpg)

**Comment by VincentG123** [comment]
[commit #](https://github.com/LearnTeachCode/visual-fractions/commit/7fe2b3c71cdbed13166c89eec41b353b0c7d3f41)
This up to the point where we refactored everything it takes to visualize the fraction given the numerator and denominator.
